version: '3'

services:
  locations-mariadb:
    image: mariadb
    restart: always
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: locations
      MYSQL_USER: locations
      MYSQL_PASSWORD: locations
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  locations-app:
    image: locations
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - locations-mariadb
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mariadb://locations-mariadb/locations'
    entrypoint: ['./wait-for-it.sh', '-t', '120', 'locations-mariadb:3306', '--', 'java', 'org.springframework.boot.loader.JarLauncher']