version: '3'

services:
  employees-mariadb:
    image: mariadb
    restart: always
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: employees
      MYSQL_USER: employees
      MYSQL_PASSWORD: employees
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  employees-app:
    image: employees
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - employees-mariadb
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mariadb://employees-mariadb/employees'
    entrypoint: ['./wait-for-it.sh', '-t', '120', 'employees-mariadb:3306', '--', 'java', 'org.springframework.boot.loader.JarLauncher']
